#include "multiplication.hpp"
#include "../precompute/gmp_wrapper.hpp"
#include <iostream>
#include <cassert>
#include <array>
#include <string>
#include <tuple>
#include "../../scripts/test_values.hpp"

template<int limbs>
bool compare_arrays(const std::array<uint64_t, limbs> &a, const std::array<uint64_t, limbs> &b, const char* name) {
    for (int i = 0; i < limbs; i++) {
        if (a[i] != b[i]) {
            std::cerr << name << " mismatch at index " << i << ": got " << a[i] << " expected " << b[i] << std::endl;
            return false;
        }
    }
    return true;
}

template<int outer, int inner>
bool compare_2d_arrays(
    const std::array<std::array<uint64_t, inner>, outer> &a,
    const std::array<std::array<uint64_t, inner>, outer> &b,
    const char* name) {
    for (int i = 0; i < outer; i++) {
        for (int j = 0; j < inner; j++) {
            if (a[i][j] != b[i][j]) {
                std::cerr << name << " mismatch at [" << i << "][" << j << "]: got " << a[i][j] << " expected " << b[i][j] << std::endl;
                return false;
            }
        }
    }
    return true;
}

int main() {
    constexpr int limbs = 8;
    constexpr int bits = 381;  // Bit length of the target modulus
    
    // Load test values
    BigInt target(modulus);
    BigInt a_val(a);
    BigInt b_val(b);
    BigInt c_expected(c_correct);
    
    // Create system using the exact moduli from test_values.hpp
    // This ensures we use the same moduli that Python used to generate the test values
    std::cout << "Creating system with exact moduli from test_values..." << std::endl;
    
    // Compute m1 and m2 from moduli
    BigInt m1(1);
    BigInt m2(1);
    for (int i = 0; i < limbs; i++) {
        m1 *= BigInt(moduli1[i]);
        m2 *= BigInt(moduli2[i]);
    }
    
    constexpr int mulbits = 52;
    const BigInt r = BigInt(1) << mulbits;
    
    const BigInt mont_factor = (BigInt(0) - target).mod_inverse(m1);
    const BigInt r_inv_m1 = r.mod_inverse(m1);
    const BigInt inv_factor = m1.mod_inverse(m2);
    
    const BigInt premult1 = (mont_factor * r_inv_m1) % m1;
    const BigInt postmult1 = ((target * inv_factor) % m2 * inv_factor % m2 * r % m2 * r) % m2;
    
    const BigInt r_inv_m2 = r.mod_inverse(m2);
    const BigInt premult2 = (m1 % m2) * r_inv_m2 % m2;
    const BigInt postmult2 = (r % m1) * (r % m1) % m1;
    
    const BigInt m1_inv_target = m1.mod_inverse(target);
    
    bool all_pass = true;
    
    // Compare premult/postmult values with Python (if available in test_values.hpp)
    // Note: These values need to be generated by Python script first
    #ifdef r1_premult_py_str
    std::cout << "Comparing premult/postmult values (C++ vs Python):" << std::endl;
    
    BigInt r1_premult_py(r1_premult_py_str);
    BigInt r1_postmult_py(r1_postmult_py_str);
    BigInt r2_premult_py(r2_premult_py_str);
    BigInt r2_postmult_py(r2_postmult_py_str);
    BigInt convert_to_premult_py(convert_to_premult_py_str);
    BigInt convert_to_postmult_py(convert_to_postmult_py_str);
    BigInt convert_from_premult_py(convert_from_premult_py_str);
    BigInt convert_from_postmult_py(convert_from_postmult_py_str);
    
    bool premult_postmult_match = true;
    
    if (premult1 != r1_premult_py) {
        std::cout << "  r1 premult MISMATCH: C++=" << premult1 << " Python=" << r1_premult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  r1 premult: MATCH ✓" << std::endl;
    }
    
    if (postmult1 != r1_postmult_py) {
        std::cout << "  r1 postmult MISMATCH: C++=" << postmult1 << " Python=" << r1_postmult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  r1 postmult: MATCH ✓" << std::endl;
    }
    
    if (premult2 != r2_premult_py) {
        std::cout << "  r2 premult MISMATCH: C++=" << premult2 << " Python=" << r2_premult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  r2 premult: MATCH ✓" << std::endl;
    }
    
    if (postmult2 != r2_postmult_py) {
        std::cout << "  r2 postmult MISMATCH: C++=" << postmult2 << " Python=" << r2_postmult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  r2 postmult: MATCH ✓" << std::endl;
    }
    
    BigInt convert_to_postmult = ((inv_factor % m2) * (r % m2) % m2 * (r % m2) % m2);
    if (m1 != convert_to_premult_py) {
        std::cout << "  convert_to premult MISMATCH: C++=" << m1 << " Python=" << convert_to_premult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  convert_to premult: MATCH ✓" << std::endl;
    }
    
    if (convert_to_postmult != convert_to_postmult_py) {
        std::cout << "  convert_to postmult MISMATCH: C++=" << convert_to_postmult << " Python=" << convert_to_postmult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  convert_to postmult: MATCH ✓" << std::endl;
    }
    
    BigInt convert_from_premult = ((m1 % m2) * r_inv_m2 % m2);
    if (convert_from_premult != convert_from_premult_py) {
        std::cout << "  convert_from premult MISMATCH: C++=" << convert_from_premult << " Python=" << convert_from_premult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  convert_from premult: MATCH ✓" << std::endl;
    }
    
    if (m1_inv_target != convert_from_postmult_py) {
        std::cout << "  convert_from postmult MISMATCH: C++=" << m1_inv_target << " Python=" << convert_from_postmult_py << std::endl;
        premult_postmult_match = false;
    } else {
        std::cout << "  convert_from postmult: MATCH ✓" << std::endl;
    }
    
    if (!premult_postmult_match) {
        all_pass = false;
        std::cout << "  Premult/postmult values DO NOT MATCH - this explains matrix differences!" << std::endl;
    } else {
        std::cout << "  All premult/postmult values MATCH ✓" << std::endl;
    }
    std::cout << std::endl;
    #else
    std::cout << "Note: Python premult/postmult values not available in test_values.hpp" << std::endl;
    std::cout << "Run 'python3 scripts/python_reduction.py' to generate them." << std::endl;
    std::cout << std::endl;
    #endif
    
    std::cout << "Creating r1 matrix (C++):" << std::endl;
    IntRNS2System<bits, limbs> sys{
        IntRNS2<MontgomeryReduce, limbs, limbs>(moduli1, moduli2, target, premult1, postmult1, premult2, postmult2),
        ConvertToRNS<bits, limbs>(m1, (inv_factor % m2) * (r % m2) % m2 * (r % m2) % m2, target, moduli2),
        ConvertFromRNS<bits, limbs>((m1 % m2) * r_inv_m2 % m2, m1_inv_target, target, moduli2),
        moduli1,
        moduli2
    };
    std::cout << "System created successfully" << std::endl;
    
    // Test MontgomeryReduce constants for reducer1 (m1)
    std::cout << "Testing reducer1 (m1) MontgomeryReduce constants..." << std::endl;
    const auto& reducer1 = sys.intrns2.m1;
    std::array<uint64_t, limbs> reducer1_mont_factor_actual, reducer1_t_squared_actual;
    reducer1.get_mont_factor(reducer1_mont_factor_actual);
    reducer1.get_t_squared(reducer1_t_squared_actual);
    // uint64_t reducer1_hi_mask_actual = reducer1.get_hi_mask();
    // uint64_t reducer1_lo_mask_actual = reducer1.get_lo_mask();
    
    if (!compare_arrays<limbs>(reducer1_mont_factor_actual, reducer1_mont_factor, "reducer1_mont_factor")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(reducer1_t_squared_actual, reducer1_t_squared, "reducer1_t_squared")) {
        all_pass = false;
    }
    // if (reducer1_hi_mask_actual != reducer1_hi_mask) {
    //     std::cout << "  reducer1_hi_mask mismatch: got " << reducer1_hi_mask_actual << " expected " << reducer1_hi_mask << std::endl;
    //     all_pass = false;
    // }
    // if (reducer1_lo_mask_actual != reducer1_lo_mask) {
    //     std::cout << "  reducer1_lo_mask mismatch: got " << reducer1_lo_mask_actual << " expected " << reducer1_lo_mask << std::endl;
    //     all_pass = false;
    // }
    if (all_pass) std::cout << "  reducer1 constants match ✓" << std::endl;
    
    // Test MontgomeryReduce constants for reducer2 (m2)
    std::cout << "Testing reducer2 (m2) MontgomeryReduce constants..." << std::endl;
    const auto& reducer2 = sys.intrns2.m2;
    std::array<uint64_t, limbs> reducer2_mont_factor_actual, reducer2_t_squared_actual;
    reducer2.get_mont_factor(reducer2_mont_factor_actual);
    reducer2.get_t_squared(reducer2_t_squared_actual);
    // uint64_t reducer2_hi_mask_actual = reducer2.get_hi_mask();
    // uint64_t reducer2_lo_mask_actual = reducer2.get_lo_mask();
    
    if (!compare_arrays<limbs>(reducer2_mont_factor_actual, reducer2_mont_factor, "reducer2_mont_factor")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(reducer2_t_squared_actual, reducer2_t_squared, "reducer2_t_squared")) {
        all_pass = false;
    }
    // if (reducer2_hi_mask_actual != reducer2_hi_mask) {
    //     std::cout << "  reducer2_hi_mask mismatch: got " << reducer2_hi_mask_actual << " expected " << reducer2_hi_mask << std::endl;
    //     all_pass = false;
    // }
    // if (reducer2_lo_mask_actual != reducer2_lo_mask) {
    //     std::cout << "  reducer2_lo_mask mismatch: got " << reducer2_lo_mask_actual << " expected " << reducer2_lo_mask << std::endl;
    //     all_pass = false;
    // }
    if (all_pass) std::cout << "  reducer2 constants match ✓" << std::endl;
    std::cout << std::endl;
    
    // Test 1: Check moduli match
    std::cout << "Testing moduli match..." << std::endl;
    if (!compare_arrays<limbs>(sys.moduli1, moduli1, "moduli1")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(sys.moduli2, moduli2, "moduli2")) {
        all_pass = false;
    }
    if (all_pass) std::cout << "  Moduli match ✓" << std::endl;
    
    // Test 2: Check r1 matrix
    std::cout << "Testing r1 matrix..." << std::endl;
    std::cout << "  r1 premult (C++): " << sys.intrns2.r1.get_premult() << std::endl;
    std::cout << "  r1 postmult (C++): " << sys.intrns2.r1.get_postmult() << std::endl;
    std::array<std::array<uint64_t, limbs>, limbs> r1_rns_mat_actual;
    std::array<uint64_t, limbs> r1_correction_actual;
    std::array<uint64_t, limbs> r1_sqe_actual;
    sys.intrns2.r1.get_rns_mat(r1_rns_mat_actual);
    sys.intrns2.r1.get_correction(r1_correction_actual);
    sys.intrns2.r1.get_shifted_quotient_estimations(r1_sqe_actual);
    
    if (!compare_2d_arrays<limbs, limbs>(r1_rns_mat_actual, r1_rns_mat, "r1_rns_mat")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(r1_correction_actual, r1_correction, "r1_correction")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(r1_sqe_actual, r1_shifted_quotient_estimations, "r1_shifted_quotient_estimations")) {
        all_pass = false;
    }
    if (all_pass) std::cout << "  r1 matrix matches ✓" << std::endl;
    
    // Test 3: Check r2 matrix
    std::cout << "Testing r2 matrix..." << std::endl;
    std::cout << "  r2 premult (C++): " << sys.intrns2.r2.get_premult() << std::endl;
    std::cout << "  r2 postmult (C++): " << sys.intrns2.r2.get_postmult() << std::endl;
    std::array<std::array<uint64_t, limbs>, limbs> r2_rns_mat_actual;
    std::array<uint64_t, limbs> r2_correction_actual;
    std::array<uint64_t, limbs> r2_sqe_actual;
    sys.intrns2.r2.get_rns_mat(r2_rns_mat_actual);
    sys.intrns2.r2.get_correction(r2_correction_actual);
    sys.intrns2.r2.get_shifted_quotient_estimations(r2_sqe_actual);
    
    if (!compare_2d_arrays<limbs, limbs>(r2_rns_mat_actual, r2_rns_mat, "r2_rns_mat")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(r2_correction_actual, r2_correction, "r2_correction")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(r2_sqe_actual, r2_shifted_quotient_estimations, "r2_shifted_quotient_estimations")) {
        all_pass = false;
    }
    if (all_pass) std::cout << "  r2 matrix matches ✓" << std::endl;
    
    // Test 4: Check convert_to matrix
    std::cout << "Testing convert_to matrix..." << std::endl;
    const auto& convert_to_mat = sys.convert_to.get_conversion_matrix();
    std::cout << "  convert_to premult (C++): " << convert_to_mat.get_premult() << std::endl;
    std::cout << "  convert_to postmult (C++): " << convert_to_mat.get_postmult() << std::endl;
    constexpr int convert_to_indigits = 8;  // ceil_div(381, 52) = 8
    // RNSMatrix<1, 8, 8, 52>: rns_mat is [in_limbs*IN_DIGITS][out_limbs*OUT_DIGITS] = [1*8][8*1] = [8][8]
    std::array<std::array<uint64_t, limbs>, convert_to_indigits> convert_to_rns_mat_actual;
    std::array<uint64_t, limbs> convert_to_correction_actual;
    std::array<uint64_t, convert_to_indigits> convert_to_sqe_actual;
    convert_to_mat.get_rns_mat(convert_to_rns_mat_actual);
    convert_to_mat.get_correction(convert_to_correction_actual);
    convert_to_mat.get_shifted_quotient_estimations(convert_to_sqe_actual);
    
    // convert_to_rns_mat in test_values is [8][8] matching our dimensions
    if (!compare_2d_arrays<convert_to_indigits, limbs>(convert_to_rns_mat_actual, convert_to_rns_mat, "convert_to_rns_mat")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(convert_to_correction_actual, convert_to_correction, "convert_to_correction")) {
        all_pass = false;
    }
    if (!compare_arrays<convert_to_indigits>(convert_to_sqe_actual, convert_to_shifted_quotient_estimations, "convert_to_shifted_quotient_estimations")) {
        all_pass = false;
    }
    if (all_pass) std::cout << "  convert_to matrix matches ✓" << std::endl;
    
    // Test 5: Check convert_from matrix
    std::cout << "Testing convert_from matrix..." << std::endl;
    const auto& convert_from_mat = sys.convert_from.get_conversion_matrix();
    std::cout << "  convert_from premult (C++): " << convert_from_mat.get_premult() << std::endl;
    std::cout << "  convert_from postmult (C++): " << convert_from_mat.get_postmult() << std::endl;
    constexpr int convert_from_outdigits = 8;  // ceil_div(381+1, 52) = 8 (matches Python's word_len(2*target, 52))
    std::array<std::array<uint64_t, convert_from_outdigits>, limbs> convert_from_rns_mat_actual;
    std::array<uint64_t, convert_from_outdigits> convert_from_correction_actual;
    std::array<uint64_t, limbs> convert_from_sqe_actual;
    convert_from_mat.get_rns_mat(convert_from_rns_mat_actual);
    convert_from_mat.get_correction(convert_from_correction_actual);
    convert_from_mat.get_shifted_quotient_estimations(convert_from_sqe_actual);
    
    // Note: convert_from has different dimensions - it's [limbs][outdigits] not [limbs][limbs]
    // The test_values.hpp might have wrong dimensions, but let's check what Python generates
    if (!compare_2d_arrays<limbs, convert_from_outdigits>(convert_from_rns_mat_actual, convert_from_rns_mat, "convert_from_rns_mat")) {
        all_pass = false;
    }
    if (!compare_arrays<convert_from_outdigits>(convert_from_correction_actual, convert_from_correction, "convert_from_correction")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(convert_from_sqe_actual, convert_from_shifted_quotient_estimations, "convert_from_shifted_quotient_estimations")) {
        all_pass = false;
    }
    if (all_pass) std::cout << "  convert_from matrix matches ✓" << std::endl;
    
    // Test 6: Convert a and b to RNS and check results
    std::cout << "Testing conversion of a and b..." << std::endl;
    AVXVector<limbs> a_m1_actual, a_m2_actual;
    AVXVector<limbs> b_m1_actual, b_m2_actual;
    
    // Convert a: using to_mont_avx
    std::tie(a_m1_actual, a_m2_actual) = sys.to_mont_avx(a_val);
    
    // Convert b: using to_mont_avx
    std::tie(b_m1_actual, b_m2_actual) = sys.to_mont_avx(b_val);
    
    std::array<uint64_t, limbs> a_m1_arr, a_m2_arr, b_m1_arr, b_m2_arr;
    a_m1_actual.store(a_m1_arr.data());
    a_m2_actual.store(a_m2_arr.data());
    b_m1_actual.store(b_m1_arr.data());
    b_m2_actual.store(b_m2_arr.data());
    
    if (!compare_arrays<limbs>(a_m1_arr, a_m1, "a_m1")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(a_m2_arr, a_m2, "a_m2")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(b_m1_arr, b_m1, "b_m1")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(b_m2_arr, b_m2, "b_m2")) {
        all_pass = false;
    }
    if (all_pass) std::cout << "  Conversion of a and b matches ✓" << std::endl;
    
    // Test 7: Multiply and check product
    std::cout << "Testing multiplication..." << std::endl;
    AVXVector<limbs> c_m1_actual, c_m2_actual;
    sys.intrns2.mul_reduce(a_m1_actual, a_m2_actual, b_m1_actual, b_m2_actual, c_m1_actual, c_m2_actual);
    
    std::array<uint64_t, limbs> c_m1_arr, c_m2_arr;
    c_m1_actual.store(c_m1_arr.data());
    c_m2_actual.store(c_m2_arr.data());
    
    if (!compare_arrays<limbs>(c_m1_arr, c_m1, "c_m1")) {
        all_pass = false;
    }
    if (!compare_arrays<limbs>(c_m2_arr, c_m2, "c_m2")) {
        all_pass = false;
    }
    if (all_pass) std::cout << "  Multiplication matches ✓" << std::endl;
    
    // Test 8: Convert back and check result
    std::cout << "Testing conversion back..." << std::endl;
    BigInt c_actual = sys.from_mont_avx(c_m2_actual);
    BigInt c_expected_mod = c_expected % target;
    BigInt c_actual_mod = c_actual % target;
    
    if (c_actual_mod != c_expected_mod) {
        std::cerr << "c mismatch: got " << c_actual_mod.to_string() << " expected " << c_expected_mod.to_string() << std::endl;
        all_pass = false;
    } else {
        std::cout << "  Conversion back matches ✓" << std::endl;
    }
    
    std::cout << std::endl << (all_pass ? "ALL TESTS PASS" : "SOME TESTS FAILED") << std::endl;
    return all_pass ? 0 : 1;
}
